In [1]:
import pandas as pd
import os
from collections import defaultdict

# High

In [2]:
high = pd.read_table("tsv/CoNLL-SIGMORPHON Shared Task 1 Results - high.tsv")
high.tail()

,Unnamed: 0,waseda-01,uzh-02,uzh-01,ua-08,ua-07,ua-06,ua-05,ua-04,ua-03,...,iitbhu-iiith-02,iitbhu-iiith-01,iit-varanasi-01,hamburg-01,bme-03,bme-02,bme-01,baseline,axsemantics-02,axsemantics-01
82,north-frisian,92.000000,95.000000,94.000000,0,0,0,0,0,0,...,96.00000,96.00000,96.000000,83.000000,94.000000,95.000000,96.000000,37.000000,33.000000,80.000000
83,old-english,83.700000,87.900000,88.700000,0,0,0,0,0,0,...,86.00000,86.00000,83.400000,50.900000,87.100000,88.200000,87.100000,40.900000,34.300000,69.300000
84,polish,89.300000,93.400000,93.000000,0,0,0,0,0,0,...,88.70000,88.70000,82.800000,76.400000,89.300000,90.800000,89.300000,87.100000,82.900000,87.600000
85,russian,88.400000,94.400000,94.000000,0,0,0,0,0,0,...,91.00000,91.00000,85.400000,85.200000,90.400000,92.000000,90.400000,86.500000,76.100000,88.000000
86,average,91.115116,95.965116,96.004651,0,0,0,0,0,0,...,94.42907,94.42907,91.733721,77.531395,93.973256,94.662791,93.884884,75.298837,74.774419,84.188372

In [3]:
high.iloc[:-1].mean().sort_values(ascending=False).astype(float).to_frame().reset_index()

/home/judit/miniconda3/lib/python3.7/site-packages/pandas/core/dtypes/cast.py:730: ComplexWarning: Casting complex values to real discards the imaginary part
  return arr.astype(dtype, copy=True)

                index              0
0              uzh-01   9.600465e+01
1              uzh-02   9.596512e+01
2              bme-02   9.466279e+01
3     iitbhu-iiith-02   9.442907e+01
4     iitbhu-iiith-01   9.442907e+01
5              bme-03   9.397326e+01
6              bme-01   9.388488e+01
7              msu-04   9.186512e+01
8     iit-varanasi-01   9.173372e+01
9           waseda-01   9.111512e+01
10             msu-03   9.052093e+01
11     axsemantics-01   8.418837e+01
12             msu-02   8.268256e+01
13         hamburg-01   7.753140e+01
14           baseline   7.529884e+01
15     axsemantics-02   7.477442e+01
16             msu-01   7.433140e+01
17           racai-01   7.249419e+01
18  tuebingen-oslo-03   6.304767e+01
19  tuebingen-oslo-02   5.659767e+01
20  tuebingen-oslo-01   4.952093e+01
21           kucst-01   4.868140e+01
22         Unnamed: 0  8.054549e-312
23              ua-01   0.000000e+00
24              ua-02   0.000000e+00
25              ua-03   0.000000e+00
26              ua-04   0.000000e+00
27              ua-05   0.000000e+00
28              ua-06   0.000000e+00
29              ua-07   0.000000e+00
30              ua-08   0.000000e+00

# Medium

In [4]:
medium = pd.read_table("tsv/CoNLL-SIGMORPHON Shared Task 1 Results - medium.tsv")
medium.iloc[:-1].mean().sort_values(ascending=False).to_frame().reset_index()

                index          0
0     iitbhu-iiith-02  84.185294
1     iitbhu-iiith-01  82.895098
2              msu-04  76.398039
3              msu-03  75.736275
4          hamburg-01  74.028431
5     iit-varanasi-01  70.173529
6              msu-02  69.449020
7              bme-01  67.430392
8              bme-03  67.357843
9              bme-02  67.258824
10           baseline  61.775490
11     axsemantics-02  60.003922
12             msu-01  54.442157
13  tuebingen-oslo-03  30.979412
14  tuebingen-oslo-02  29.721569
15           kucst-01  29.118627
16  tuebingen-oslo-01  20.972549
17     axsemantics-01   9.098039
18          languages   0.941222
19          waseda-01   0.940834
20             uzh-02   0.928067
21             uzh-01   0.925775
22              ua-01   0.000000
23              ua-02   0.000000
24              ua-03   0.000000
25              ua-04   0.000000
26              ua-05   0.000000
27              ua-06   0.000000
28              ua-07   0.000000
29              ua-08   0.000000
30           racai-01   0.000000

# Low

In [5]:
low = pd.read_table("tsv/CoNLL-SIGMORPHON Shared Task 1 Results - low.tsv")
low.iloc[:-1].mean().sort_values(ascending=False).to_frame().reset_index()

                index          0
0              uzh-02  57.213592
1              uzh-01  57.180583
2               ua-08  53.215534
3     iitbhu-iiith-02  52.596117
4               ua-05  50.533981
5     iitbhu-iiith-01  49.791262
6               ua-06  49.733981
7               ua-03  44.820388
8           waseda-01  44.087379
9              msu-02  41.612621
10         hamburg-01  40.282524
11              ua-02  39.187379
12              ua-01  38.218447
13           baseline  38.198058
14              ua-07  37.985437
15             msu-04  31.396117
16             msu-03  25.855340
17    iit-varanasi-01  23.330097
18              ua-04  21.250485
19     axsemantics-02  14.740777
20  tuebingen-oslo-02   4.428155
21             bme-01   3.742718
22             bme-03   3.634951
23           kucst-01   2.516505
24             bme-02   2.429126
25  tuebingen-oslo-03   1.388350
26  tuebingen-oslo-01   0.000000
27             msu-01   0.000000
28           racai-01   0.000000

In [6]:
r = high.iloc[:-1].mean()  
r[r.index.str.startswith('bme')].sort_index()

bme-01    93.884884
bme-02    94.662791
bme-03    93.973256
dtype: float64

In [7]:
r = medium.iloc[:-1].mean()  
r[r.index.str.startswith('bme')].sort_index()

bme-01    67.430392
bme-02    67.258824
bme-03    67.357843
dtype: float64

In [8]:
r = low.iloc[:-1].mean()  
r[r.index.str.startswith('bme')].sort_index()

bme-01    3.742718
bme-02    2.429126
bme-03    3.634951
dtype: float64

# Training data stats

In [19]:
DATA_DIR = "/home/judit/repo/external/conll2018/task1/all"
SURPRISE_DIR = "/home/judit/repo/external/conll2018/task1/surprise"

def load_stats(fn):
    maxlen_lemma = 0
    maxlen_infl = 0
    maxlen_tags = 0
    types_lemma = set()
    types_infl = set()
    types_tags = set()
    alphabet = set()
    cnt = 0
    sumlen_lemma = 0
    sumlen_infl = 0
    sumlen_tags = 0
    upper_cnt = 0
    with open(fn) as f:
        for l in f:
            cnt += 1
            lemma, infl, tags = l.rstrip('\n').split('\t')
            tags = tags.split(';')
            maxlen_lemma = max(maxlen_lemma, len(lemma))
            maxlen_infl = max(maxlen_infl, len(infl))
            maxlen_tags = max(maxlen_tags, len(tags))
            sumlen_lemma += len(lemma)
            sumlen_infl += len(infl)
            sumlen_tags += len(tags)
            alphabet |= set(lemma)
            alphabet |= set(infl)
            types_lemma.add(lemma)
            types_infl.add(infl)
            types_tags |= set(tags)
            upper_cnt += sum(c.isupper() for c in lemma)
    return {
        'lemma maxlen': maxlen_lemma,
        'inflected maxlen': maxlen_infl,
        'tags maxlen': maxlen_tags,
        'alphabet size': len(alphabet),
        'lemma types': len(types_lemma),
        'inflected types': len(types_infl),
        'tag types': len(types_tags),
        'lemma avglen' : sumlen_lemma / cnt,
        'infl avglen' : sumlen_infl / cnt,
        'tags avglen' : sumlen_tags / cnt,
        'upper ratio': upper_cnt / sumlen_lemma,
    }
        
stats = []
for fn in os.listdir(DATA_DIR):
    if fn.endswith('train-high'):
        stat = load_stats(os.path.join(DATA_DIR, fn))
        stat['language'] = '-'.join(fn.split('-')[:-2])
        stats.append(stat)
for fn in os.listdir(SURPRISE_DIR):
    if fn.endswith('train-high'):
        stat = load_stats(os.path.join(SURPRISE_DIR, fn))
        stat['language'] = '-'.join(fn.split('-')[:-2])
        stats.append(stat)
    
stats = pd.DataFrame(stats).set_index('language').sort_index()

# Analysis

In [20]:
df = high.rename(columns={'Unnamed: 0': 'language'}).set_index('language')
print(df['bme-02'].quantile(.8))
good = df[df['bme-02'] >= df['bme-02'].quantile(.8)]
good

99.0

,waseda-01,uzh-02,uzh-01,ua-08,ua-07,ua-06,ua-05,ua-04,ua-03,ua-02,...,iitbhu-iiith-02,iitbhu-iiith-01,iit-varanasi-01,hamburg-01,bme-03,bme-02,bme-01,baseline,axsemantics-02,axsemantics-01
language,,,,,,,,,,,,,,,,,,,,,
bashkir,93.2,99.9,99.9,0,0,0,0,0,0,0,...,99.8,99.8,99.7,99.1,99.8,99.8,99.8,90.7,99.8,99.8
bengali,98.0,99.0,99.0,0,0,0,0,0,0,0,...,99.0,99.0,99.0,93.0,99.0,99.0,99.0,81.0,78.0,96.0
classical-syriac,98.0,100.0,100.0,0,0,0,0,0,0,0,...,99.0,99.0,100.0,100.0,98.0,99.0,97.0,97.0,99.0,100.0
crimean-tatar,97.0,98.0,98.0,0,0,0,0,0,0,0,...,99.0,99.0,100.0,98.0,99.0,99.0,99.0,95.0,98.0,98.0
friulian,99.0,99.0,99.0,0,0,0,0,0,0,0,...,99.0,99.0,99.0,85.0,99.0,99.0,99.0,96.0,99.0,97.0
galician,98.6,99.3,99.5,0,0,0,0,0,0,0,...,98.9,98.9,98.7,93.9,99.2,99.3,99.2,95.1,95.0,96.7
haida,66.0,99.0,99.0,0,0,0,0,0,0,0,...,93.0,93.0,100.0,15.0,100.0,99.0,100.0,66.0,100.0,93.0
hebrew,98.4,99.3,99.5,0,0,0,0,0,0,0,...,98.8,98.8,97.3,83.7,98.5,99.3,98.5,53.7,54.5,84.3
hindi,73.6,100.0,100.0,0,0,0,0,0,0,0,...,99.7,99.7,99.4,98.7,99.9,100.0,100.0,93.0,80.0,100.0
kabardian,95.0,96.0,99.0,0,0,0,0,0,0,0,...,99.0,99.0,99.0,100.0,98.0,99.0,98.0,86.0,99.0,99.0
khaling,99.4,99.6,99.7,0,0,0,0,0,0,0,...,99.5,99.5,98.4,77.3,99.0,99.6,99.6,53.7,17.1,72.0
middle-french,98.7,99.3,99.2,0,0,0,0,0,0,0,...,98.7,98.7,96.7,93.5,98.6,99.0,98.6,95.1,95.4,97.0
occitan,98.0,99.0,99.0,0,0,0,0,0,0,0,...,98.0,98.0,99.0,83.0,97.0,99.0,97.0,96.0,92.0,94.0
persian,62.9,99.8,99.8,0,0,0,0,0,0,0,...,99.7,99.7,98.9,90.8,99.6,99.9,99.5,80.7,62.6,63.7
quechua,95.1,99.9,99.9,0,0,0,0,0,0,0,...,99.5,99.5,99.4,81.0,99.3,99.6,99.3,95.1,98.8,99.8
swahili,98.0,99.0,99.0,0,0,0,0,0,0,0,...,99.0,99.0,100.0,98.0,100.0,100.0,99.0,0.0,1.0,98.0
urdu,97.3,99.5,99.5,0,0,0,0,0,0,0,...,100.0,100.0,99.7,99.0,99.2,99.3,99.4,95.9,83.7,99.3
uzbek,93.0,100.0,100.0,0,0,0,0,0,0,0,...,100.0,100.0,98.0,100.0,100.0,100.0,100.0,96.0,99.0,100.0
yiddish,98.0,100.0,100.0,0,0,0,0,0,0,0,...,100.0,100.0,99.0,96.0,99.0,99.0,98.0,94.0,99.0,97.0
zulu,98.9,99.7,99.8,0,0,0,0,0,0,0,...,99.3,99.3,97.2,98.5,99.2,99.0,98.1,0.2,2.5,93.8
kannada,99.0,100.0,100.0,0,0,0,0,0,0,0,...,98.0,98.0,100.0,91.0,100.0,100.0,99.0,66.0,97.0,90.0

## Overall stats for all languages

In [21]:
stats.describe()

,alphabet size,infl avglen,inflected maxlen,inflected types,lemma avglen,lemma maxlen,lemma types,tag types,tags avglen,tags maxlen,upper ratio
count,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000
mean,42.755814,9.159997,24.255814,7650.534884,6.883528,18.860465,2308.348837,25.325581,4.415738,6.081395,0.001359
std,15.179658,1.894080,10.857566,2887.857511,1.352391,10.412846,2480.044092,8.282429,1.124486,1.854820,0.006304
min,19.000000,5.517600,10.000000,631.000000,3.828600,6.000000,15.000000,7.000000,2.049266,3.000000,0.000000
25%,31.000000,8.119794,18.250000,6648.250000,5.829803,14.000000,259.250000,19.250000,3.663575,5.000000,0.000000
50%,40.000000,9.004500,22.000000,9101.500000,6.969650,17.000000,1065.000000,25.000000,4.249270,6.000000,0.000000
75%,54.750000,10.081028,27.000000,9766.000000,7.778550,21.000000,4063.250000,30.750000,5.001112,7.000000,0.000638
max,102.000000,17.059649,90.000000,9994.000000,10.050200,89.000000,8643.000000,48.000000,8.631800,14.000000,0.056466

## Same stats for top 20% languages

In [22]:
good[['bme-02']].join(stats)

,bme-02,alphabet size,infl avglen,inflected maxlen,inflected types,lemma avglen,lemma maxlen,lemma types,tag types,tags avglen,tags maxlen,upper ratio
language,,,,,,,,,,,,
bashkir,99.8,55,8.616200,22,9106,5.504400,16,1084,11,3.336100,4,0.002780
bengali,99.0,49,7.771624,23,3746,6.033231,18,136,26,4.122319,5,0.000000
classical-syriac,99.0,22,5.796745,10,1927,5.217863,8,160,19,3.077212,4,0.000000
crimean-tatar,99.0,40,8.446541,20,7123,6.583949,17,1230,17,2.051135,4,0.001184
friulian,99.0,29,7.479736,15,4953,5.145344,9,168,20,5.000381,6,0.000000
galician,99.3,29,8.671600,17,8890,6.988100,12,486,25,5.029000,6,0.000000
haida,99.0,30,17.059649,39,6605,6.422076,14,41,30,4.308041,7,0.000000
hebrew,99.3,29,5.517600,13,8836,3.974500,9,510,24,4.536100,5,0.000000
hindi,100.0,55,11.176500,27,8709,6.951300,20,258,25,5.809900,6,0.000000
kabardian,99.0,33,8.809820,22,2786,5.725795,16,250,10,3.518326,4,0.002053
khaling,99.6,32,7.917300,14,8680,3.828600,6,584,26,8.291300,9,0.000000
middle-french,99.0,28,9.687800,22,9134,7.991900,14,603,21,5.358900,7,0.000000
occitan,99.0,31,8.129374,17,7308,6.524519,10,174,20,5.001355,6,0.000000
persian,99.9,36,11.612700,32,9186,8.526300,22,273,21,4.962000,6,0.000000
quechua,99.6,23,13.645300,27,9880,5.691400,14,957,46,4.034400,5,0.000334
swahili,100.0,24,8.137727,16,6355,4.582500,9,100,32,6.531591,8,0.000000
urdu,99.3,41,10.801900,24,5142,6.386300,14,182,29,5.635200,6,0.000000
uzbek,100.0,21,11.559434,21,939,5.644340,9,15,15,3.856604,4,0.000000
yiddish,99.0,37,7.647363,22,3422,7.348015,21,803,27,4.578439,5,0.000000
zulu,99.0,46,8.707300,21,9163,6.282200,17,566,48,3.655900,6,0.015345
kannada,100.0,49,7.014146,22,2931,5.051563,16,159,28,3.883641,5,0.000000

# Bottom 20%

In [23]:
print(df['bme-02'].quantile(.2))
bad = df[df['bme-02'] <= df['bme-02'].quantile(.2)]
bad

90.83999999999999

,waseda-01,uzh-02,uzh-01,ua-08,ua-07,ua-06,ua-05,ua-04,ua-03,ua-02,...,iitbhu-iiith-02,iitbhu-iiith-01,iit-varanasi-01,hamburg-01,bme-03,bme-02,bme-01,baseline,axsemantics-02,axsemantics-01
language,,,,,,,,,,,,,,,,,,,,,
danish,90.7,94.6,95.5,0,0,0,0,0,0,0,...,91.5,91.5,91.3,76.0,89.4,90.4,89.4,87.0,90.4,92.7
faroese,81.3,86.4,85.6,0,0,0,0,0,0,0,...,83.9,83.9,81.1,56.3,83.8,87.1,85.3,76.1,76.8,79.6
greek,83.7,91.0,91.7,0,0,0,0,0,0,0,...,88.2,88.2,80.8,58.9,86.6,89.1,86.6,78.3,54.8,78.2
hungarian,79.6,86.6,87.2,0,0,0,0,0,0,0,...,85.9,85.9,82.3,59.2,83.7,85.5,83.7,68.8,80.9,76.9
icelandic,81.9,91.1,91.3,0,0,0,0,0,0,0,...,85.0,85.0,83.9,55.2,86.0,87.0,86.0,76.9,79.3,80.9
latin,65.4,74.6,75.9,0,0,0,0,0,0,0,...,73.7,73.7,61.5,18.1,77.4,78.9,77.4,47.6,37.2,46.2
livonian,94.0,100.0,98.0,0,0,0,0,0,0,0,...,98.0,98.0,97.0,68.0,92.0,87.0,92.0,67.0,76.0,82.0
norwegian-bokmaal,90.5,92.1,92.0,0,0,0,0,0,0,0,...,89.0,89.0,89.0,81.7,88.2,88.3,88.2,91.0,87.2,90.8
norwegian-nynorsk,83.4,94.9,94.6,0,0,0,0,0,0,0,...,84.6,84.6,82.6,56.6,90.8,85.3,90.8,74.8,88.0,82.8
old-armenian,88.8,90.4,90.4,0,0,0,0,0,0,0,...,89.1,89.1,87.3,68.0,87.7,89.3,87.7,79.2,82.2,84.9
romanian,83.2,89.0,88.3,0,0,0,0,0,0,0,...,85.8,85.8,79.0,69.2,84.1,87.9,85.2,79.8,62.4,82.6
sorani,88.3,90.6,90.6,0,0,0,0,0,0,0,...,89.5,89.5,89.0,59.3,89.5,88.9,89.5,63.6,27.6,76.0
swedish,88.1,93.1,93.3,0,0,0,0,0,0,0,...,88.1,88.1,87.2,75.6,88.4,89.3,88.4,84.7,88.5,88.0
votic,80.0,90.0,88.0,0,0,0,0,0,0,0,...,82.0,82.0,66.0,41.0,85.0,84.0,79.0,34.0,66.0,37.0
french,84.8,90.4,90.2,0,0,0,0,0,0,0,...,87.6,87.6,81.1,72.5,86.4,88.1,86.4,83.0,79.6,85.3
german,87.5,90.2,89.7,0,0,0,0,0,0,0,...,87.6,87.6,83.7,77.1,86.2,88.5,86.2,81.1,82.3,82.3
old-english,83.7,87.9,88.7,0,0,0,0,0,0,0,...,86.0,86.0,83.4,50.9,87.1,88.2,87.1,40.9,34.3,69.3
polish,89.3,93.4,93.0,0,0,0,0,0,0,0,...,88.7,88.7,82.8,76.4,89.3,90.8,89.3,87.1,82.9,87.6

## Stat table again

In [24]:
stats.describe()

,alphabet size,infl avglen,inflected maxlen,inflected types,lemma avglen,lemma maxlen,lemma types,tag types,tags avglen,tags maxlen,upper ratio
count,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000
mean,42.755814,9.159997,24.255814,7650.534884,6.883528,18.860465,2308.348837,25.325581,4.415738,6.081395,0.001359
std,15.179658,1.894080,10.857566,2887.857511,1.352391,10.412846,2480.044092,8.282429,1.124486,1.854820,0.006304
min,19.000000,5.517600,10.000000,631.000000,3.828600,6.000000,15.000000,7.000000,2.049266,3.000000,0.000000
25%,31.000000,8.119794,18.250000,6648.250000,5.829803,14.000000,259.250000,19.250000,3.663575,5.000000,0.000000
50%,40.000000,9.004500,22.000000,9101.500000,6.969650,17.000000,1065.000000,25.000000,4.249270,6.000000,0.000000
75%,54.750000,10.081028,27.000000,9766.000000,7.778550,21.000000,4063.250000,30.750000,5.001112,7.000000,0.000638
max,102.000000,17.059649,90.000000,9994.000000,10.050200,89.000000,8643.000000,48.000000,8.631800,14.000000,0.056466

## Same stats for bottom 20%

In [25]:
bad[['bme-02']].join(stats)

,bme-02,alphabet size,infl avglen,inflected maxlen,inflected types,lemma avglen,lemma maxlen,lemma types,tag types,tags avglen,tags maxlen,upper ratio
language,,,,,,,,,,,,
danish,90.4,46,9.145100,27,9768,7.497600,24,3137,16,3.966700,4,0.000547
faroese,87.1,34,8.116600,22,9040,6.943600,20,2959,26,3.933600,5,0.000187
greek,89.1,102,10.388300,23,9674,8.648300,21,5130,31,4.086700,6,0.002694
hungarian,85.5,55,11.383300,27,9954,8.141100,22,7123,35,3.410100,6,0.000454
icelandic,87.0,55,8.183300,26,9416,6.706100,23,4115,21,4.121200,5,0.001327
latin,78.9,55,10.351200,23,9896,8.524900,19,6517,33,4.586300,7,0.000669
livonian,87.0,40,8.590705,21,3090,6.202535,16,203,38,4.095062,10,0.000000
norwegian-bokmaal,88.3,40,9.037700,30,9868,7.436700,28,5041,21,2.881000,4,0.000148
norwegian-nynorsk,85.3,46,8.569300,22,9222,7.053500,19,4420,23,2.885400,4,0.000482
old-armenian,89.3,49,7.406900,20,9412,6.201500,19,3413,44,5.439200,8,0.000000
romanian,87.9,62,9.378400,23,9621,6.675100,19,3351,30,4.858400,6,0.000075
sorani,88.9,36,8.864500,19,9992,5.396600,14,263,34,6.040100,12,0.000000
swedish,89.3,54,10.077300,36,9769,8.433500,34,6508,23,3.695400,5,0.000391
votic,84.0,27,6.882927,15,1205,4.615447,7,55,16,3.000000,3,0.000000
french,88.1,45,9.891300,23,9887,8.374100,19,5592,19,4.882200,6,0.000000
german,88.5,64,9.935000,31,9343,9.395000,30,6797,18,3.771700,5,0.056466
old-english,88.2,47,7.307300,17,6778,6.363000,15,1795,25,4.190500,5,0.000880
polish,90.8,58,9.577500,33,9724,8.020000,33,5922,32,3.659100,6,0.001297

# bme-02 wins on these languages

In [26]:
df.loc[df.idxmax(axis=1) == 'bme-02'][['bme-02', 'uzh-01', 'uzh-02']]

          bme-02  uzh-01  uzh-02
language
albanian    98.9    97.7    96.5
armenian    96.9    96.4    96.8
faroese     87.1    85.6    86.4
latin       78.9    75.9    74.6
navajo      91.0    88.1    87.4
persian     99.9    99.8    99.8

# bme-02 is worse than best-sigma on these language

In [27]:
df.loc[df.max(axis=1) - df.std(axis=1) > df['bme-02']]

Empty DataFrame
Columns: [waseda-01, uzh-02, uzh-01, ua-08, ua-07, ua-06, ua-05, ua-04, ua-03, ua-02, ua-01, tuebingen-oslo-03, tuebingen-oslo-02, tuebingen-oslo-01, racai-01, msu-04, msu-03, msu-02, msu-01, kucst-01, iitbhu-iiith-02, iitbhu-iiith-01, iit-varanasi-01, hamburg-01, bme-03, bme-02, bme-01, baseline, axsemantics-02, axsemantics-01]
Index: []

[0 rows x 30 columns]

# bme-02 is worse than mean acc on these language

In [28]:
df.loc[df.mean(axis=1) > df['bme-02']]

Empty DataFrame
Columns: [waseda-01, uzh-02, uzh-01, ua-08, ua-07, ua-06, ua-05, ua-04, ua-03, ua-02, ua-01, tuebingen-oslo-03, tuebingen-oslo-02, tuebingen-oslo-01, racai-01, msu-04, msu-03, msu-02, msu-01, kucst-01, iitbhu-iiith-02, iitbhu-iiith-01, iit-varanasi-01, hamburg-01, bme-03, bme-02, bme-01, baseline, axsemantics-02, axsemantics-01]
Index: []

[0 rows x 30 columns]

# bme-02 is better than mean + sigma

The best teams are listed.

In [29]:
d = df.loc[df.mean(axis=1) + df.std(axis=1) < df['bme-02']]
d[d.idxmax(axis=1).unique()]

               uzh-01  uzh-02  bme-02  iitbhu-iiith-02
language
arabic           93.7    93.5    92.2             93.3
basque           98.9    98.7    98.9             98.6
belarusian       94.9    94.7    93.1             92.1
finnish          95.4    94.9    93.3             92.3
irish            91.4    91.5    91.1             87.6
khaling          99.7    99.6    99.6             99.5
latin            75.9    74.6    78.9             73.7
maltese          96.0    97.0    94.0             95.0
navajo           88.1    87.4    91.0             83.5
slovene          97.4    97.3    94.9             94.8
votic            88.0    90.0    84.0             82.0
north-frisian    94.0    95.0    95.0             96.0
old-english      88.7    87.9    88.2             86.0

# bme-02 is better than mean + 2\*sigma

In [30]:
df.loc[df.mean(axis=1) + 2*2*df.std(axis=1) < df['bme-02']]

Empty DataFrame
Columns: [waseda-01, uzh-02, uzh-01, ua-08, ua-07, ua-06, ua-05, ua-04, ua-03, ua-02, ua-01, tuebingen-oslo-03, tuebingen-oslo-02, tuebingen-oslo-01, racai-01, msu-04, msu-03, msu-02, msu-01, kucst-01, iitbhu-iiith-02, iitbhu-iiith-01, iit-varanasi-01, hamburg-01, bme-03, bme-02, bme-01, baseline, axsemantics-02, axsemantics-01]
Index: []

[0 rows x 30 columns]